version: '3'

services:
  bot_schedule:
    build: .
    command: python main.py
    restart: unless-stopped
    environment:
      MONGO_DB_HOST: mongo
      MONGO_DB_NAME: aiogram_fsm
      MONGO_DB_PORT: 27017
      DB_HOST: mysql
      DB_USER: aiogram
      DB_PASS: aiogram
      DB_NAME: schedule_bot_db
      BOT_TOKEN:
    links:
      - mysql
      - mongo
    depends_on:
      - mongo
      - mysql

  mysql:
    image: mysql:8.0.31
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: schedule_bot_db
      MYSQL_USER: aiogram
      MYSQL_PASSWORD: aiogram
      MYSQL_ROOT_PASSWORD: aiogram
    volumes:
      - my-db:/var/lib/mysql

  mongo:
    image: mongo:6.0.2
    restart: unless-stopped
    ports:
      - "27017:27017"

volumes:
  my-db: