version: '3'

services:
  bot_schedule:
    build: .
    command: >
      sh -c "alembic upgrade head && python3 main.py"
    restart: unless-stopped
    environment:
      MONGO_DB_HOST: mongo
      MONGO_DB_NAME: aiogram_fsm
      MONGO_DB_PORT: 27017
      DB_HOST: postgresql
      DB_USER: aiogram
      DB_PASS: aiogram
      DB_NAME: schedule_bot_db
    env_file:
      - .env
    links:
      - postgresql
      - redis
    depends_on:
      - redis
      - postgresql

  postgresql:
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aiogram
      POSTGRES_PASSWORD: aiogram
      POSTGRES_DB: schedule_bot_db
    volumes:
      - ./data/db:/var/lib/postgresql/data

  redis:
    image: redis:7.0.9
    restart: unless-stopped
    ports:
      - "6379:6379"