version: '3'

services:
  bot_schedule:
    build: .
    command: python main.py
    restart: unless-stopped
    environment:
      MONGO_DB_HOST: mongo
      MONGO_DB_NAME: aiogram_fsm
      MONGO_DB_PORT: 27017
      DB_HOST: postgresql
      DB_USER: aiogram
      DB_PASS: aiogram
      DB_NAME: schedule_bot_db
      BOT_TOKEN: 5740240406:AAHqlN-bos-fmmuKAjrkwHp-NFujf_0sk5E
      LOGURU_LEVEL: WARNING
    links:
      - postgresql
      - mongo
    depends_on:
      - mongo
      - postgresql

  postgresql:
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aiogram
      POSTGRES_PASSWORD: aiogram
      POSTGRES_DB: schedule_bot_db
    volumes:
      - ./data/db:/var/lib/postgresql/data

  mongo:
    image: mongo:6.0.2
    restart: unless-stopped
    ports:
      - "27017:27017"