version: '3'

services:
  bot_schedule:
    build: .
    command: python main.py
    restart: unless-stopped
#    ports:
#      - "5000:5000"
    environment:
      MONGO_DB_HOST: mongo
      MONGO_DB_NAME: aiogram_fsm
      MONGO_DB_PORT: 27017
      DB_HOST: mysql
      DB_USER: vlad_mysql
      DB_PASS: test
      DB_NAME: schedule_bot_db
      BOT_TOKEN: 5639078066:AAEpM51k2G0zxH5PwLxSBQR7UNqFZFY80Ok
    links:
      - mysql
      - mongo
    depends_on:
      - mongo
      - mysql

  mysql:
    image: mysql:8.0.31
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: schedule_bot_db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: vlad_mysql
      # You can use whatever password you like
      MYSQL_PASSWORD: test
      # Password for root access
      MYSQL_ROOT_PASSWORD: test
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  mongo:
    image: mongo:6.0.2
    restart: unless-stopped
    ports:
      - "27017:27017"

volumes:
  my-db: