"""delete unique for group title

Revision ID: 2a73181af306
Revises: 3e25b5b80864
Create Date: 2022-11-07 11:04:40.287642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a73181af306'
down_revision = '3e25b5b80864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('1')
    op.drop_index('title', table_name='bot_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'bot_groups', ['title'], unique=False)
    op.create_table('1',
    sa.Column('C1', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('C2', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('C3', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('C4', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('C5', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('C6', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
