"""created UniqueConstraint for title (Group) and department_id

Revision ID: 77f8b5007ffd
Revises: 2a73181af306
Create Date: 2022-11-19 17:32:23.744329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f8b5007ffd'
down_revision = '2a73181af306'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_department_id_title_str_uc', 'bot_groups', ['department_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_department_id_title_str_uc', 'bot_groups', type_='unique')
    # ### end Alembic commands ###
